"use strict";
// Conditional Tests:
let car = "subaru";
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car != 'honda'? I predict True.");
console.log(car != 'honda');
console.log("Is car != 'Subaru'? I predict True.");
console.log(car != 'Subaru');
console.log("Is car === 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car !== 'civic'? I predict True.");
console.log(car !== 'civic');
console.log("Is car != 'subaru'? I predict False.");
console.log(car != 'subaru');
console.log("Is car !== 'subaru'? I predict False.");
console.log(car !== 'subaru');
console.log("Is car === 'sabaru'? I predict False.");
console.log(car === 'sabaru');
let age = 25;
console.log("Is age > 26? I predict False.");
console.log(age > 26);
console.log("Is age < 20? I predict False.");
console.log(age < 20);
